### ISSUE TITLE
failed login

### ISSUE THREAD

**Issue by amandaxay** [tamnguyen98/wsuv-time-logger#1]
```Traceback (most recent call last):
  File "/Users/amandasouriyamath/Downloads/wsuv-time-logger/main.py", line 114, in <module>
    b.process_shifts(schedule)
  File "/Users/amandasouriyamath/Downloads/wsuv-time-logger/main.py", line 72, in process_shifts
    self.fill_time(shift, info)
  File "/Users/amandasouriyamath/Downloads/wsuv-time-logger/main.py", line 86, in fill_time
    self.driver.find_element_by_xpath("//*[@id=\"ContentPane_txtStartHourQuick\"]").send_keys(info['start']['hour'])
  File "/Users/amandasouriyamath/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/amandasouriyamath/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/amandasouriyamath/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/amandasouriyamath/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="ContentPane_txtStartHourQuick"]"}
  (Session info: chrome=80.0.3987.100)
```

**Comment by amandaxay** [comment]
```{
  "Monday": {
    "Labs": {
      "start": {
        "hour": "9",
        "min": "00",
        "period": "AM"
      },
      "end": {
        "hour": "10",
        "min": "00",
        "period": "AM"
      },
      "isWorkStudy": true
    },
    "HelpDesk": {
      "start": {
        "hour": "1",
        "min": "00",
        "period": "PM"
      },
      "end": {
        "hour": "3",
        "min": "00",
        "period": "PM"
      },
      "isWorkStudy": true
    },
    "Labs": {
      "start": {
        "hour": "3",
        "min": "00",
        "period": "PM"
      },
      "end": {
        "hour": "6",
        "min": "00",
        "period": "PM"
      },
      "isWorkStudy": true
    }
  },
  "Tuesday": {
    "VCS": {
      "start": {
        "hour": "10",
        "min": "00",
        "period": "AM"
      },
      "end": {
        "hour": "12",
        "min": "00",
        "period": "PM"
      },
      "isWorkStudy": true
    }
  },
  "Wednesday": {
    "VCS": {
      "start": {
        "hour": "12",
        "min": "00",
        "period": "PM"
      },
      "end": {
        "hour": "3",
        "min": "00",
        "period": "PM"
      },
      "isWorkStudy": true
    }
  },
  "Thursday": {
    "VCS": {
      "start": {
        "hour": "10",
        "min": "00",
        "period": "AM"
      },
      "end": {
        "hour": "12",
        "min": "00",
        "period": "PM"
      },
      "isWorkStudy": true
    }
  },
  "Friday": {
    "Labs": {
      "start": {
        "hour": "1",
        "min": "30",
        "period": "PM"
      },
      "end": {
        "hour": "3",
        "min": "00",
        "period": "PM"
      },
      "isWorkStudy": true
    }
  }
}```
